### ISSUE TITLE
Consider removing this repository

### ISSUE THREAD

**Issue by macbre** [Wikia/js-delayed-hover#4]
As this code is not used in our app we decided to remove it - https://github.com/Wikia/app/pull/13313

@kvas-damian - does it make sense to keep this repository?

**Comment by drets** [comment]
Why I am still watching this repo :smile:

**Comment by kvas-damian** [comment]
IMO fact that we're not using it in app doesn't mean we have to remove this repository. 
I would keep it here if we decide to use it in other use-case.
